import React from 'react';

const Contact = (props) => {
    // setTimeout(() => { //programmatic REDIRECT to the page you want
    //     props.history.push('/about') //props automatically generated by Router pack in the component
    // }, 2000);
    return(
        <div className="container">
            <h4 className="center">Contact</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
        </div>
    )
}

export default Contact;